# =================================================================
# Mosquitto Access Control List (ACL)
# Zero Trust IoT Security Framework
# =================================================================

# Anonymous default pattern permissions (Permitted to publish telemetry, intercepted by backend PDP)
pattern readwrite iot/%u/#
pattern readwrite iot/+/telemetry
pattern readwrite iot/+/status
pattern readwrite iot/+/alerts
pattern readwrite iot/+/control
pattern readwrite iot/broadcast/#
pattern readwrite $SYS/#
